### ISSUE TITLE
Review and Merging rules

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/organizational#10]
I may mix this up with my other project, but was it always, that a single reviewer was enough for merging something?

I think it makes sense to have at least 2 reviewers (they dont even need to be maintainers)

**Comment by sreichel** [comment]
Agreed.

**Comment by LeeSaferite** [comment]
Well, you cannot force 2 approvals in GH, but the original idea was that you required 2 approvals to merge a PR.

**Comment by Flyingmana** [comment]
right, we can not enforce this via settings in Github, but we could at least write it down in a central place to refer to, in case someone forgets it, or gets new added to the team.
