### ISSUE TITLE
Public communication channel

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/organizational#2]
As this project gets more and more Interest, we should maybe also decide for a central place for chit-chat.
I know there are already a few Magento centred Slacks, but they are not public accessible, also Slack does not really like being used in this way (they did an official statement about this).
IRC would be an option, but thats to to old and technical for most people and has bad mobile support.
Skype is not good for bigger and dynamic groups.
https://gitter.im/ would also be an option, but adaption proved to be not so good inside the magento community.

My current favorite is https://discordapp.com which is more targeted at gamers, but I know they also host some bigger Open Source communities, or at least one. Did not try their mobile app yet, but as gamers are picky, it will probably work quite good.

**Comment by inluxc** [comment]
discordapp.com  + 1

**Comment by sreichel** [comment]
What about hipchat?

**Comment by LeeSaferite** [comment]
As a current user of Slack and Discord, I'd personally suggest one of those.

**Comment by sreichel** [comment]
Only "hipchat" might have been a bit too short:)

Hipchat only makes sense if it is linked to Bitbucket, JIRA, (Bamboo etc.).

So I don't care... :)

**Comment by Flyingmana** [comment]
3 people who would use it are enough for me, I created a discord server and anyone can join with https://discord.gg/EV8aNbU

**Comment by inluxc** [comment]
We have always Stride from atlassian, has github integration. it would be cool.. 
Stride will replace Hipchat

https://www.stride.com/
